application: guestbook-example
version: 1
runtime: python27
module: default
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: guestbook.app

libraries:
- name: webapp2
  version: latest
